(function() {
  'use strict';

  angular
    .module('CoherentDemos')
    .service('CatalogService', CatalogService);

  /** @ngInject */
  function CatalogService($http) {
    var vm = this;

    vm.coreSolutions = [
      {name: "Actuarial Modelling", keywords: "Actuarial"},  
      {name: "Data Management", keywords: "Data Management"},
      {name: "ESG", keywords: "ESG"}, 
      {name: "EUC", keywords: "EUC"}, 
      {name: "Explainer", keywords: "Explainer"}, 
      {name: "Finance", keywords: "Reconcillation / Finance / Stress Test / Risk Modelling"},
      {name: "Pensions", keywords: "Pension / 401k / Secure 2.0"}, 
      {name: "Legacy Modernization", keywords: "Legacy"}, 
      {name: "Loan Management", keywords: "Loan / ECL"},  
      {name: "Modular Product", keywords: "Modular / Embedded"},  
      {name: "Rating / Pricing", keywords: "Rater / Explainer / Insurance"}, 
      {name: "Securities Services", keywords: "Securities Services"}
    ];

    vm.Features = [
      {name: "Complex Modelling", keywords: "Complex Modelling"}, 
      {name: "xCall", keywords: "xCall"}, 
      {name: "Data Consolidation", keywords: "Data Consolidation"}, 
      {name: "Goal Seek", keywords: "Goal Seek"}, 
      {name: "Data Illustration", keywords: "Data Illustration"}, 
      {name: "Goal Seek", keywords: "Goal Seek"}, 
      {name: "EUC", keywords: "EUC"}, 
      {name: "Spark Shell", keywords: "Spark Shell"}
    ];

    // Catalog API Call
    vm.getCatalog = function(input) {
      return new Promise(function(resolve, reject) {
        var req = {
          method: 'POST',
          url: vm.apiConstants.catalog.url,
          headers: {
            'SecretKey': vm.apiConstants.catalog.apikey,
            'x-tenant-name': vm.apiConstants.catalog.tenant
          },
          data: input
        };

        $http(req).then(
          function(response) {
            resolve(response.data.response_data.outputs);
          },
          function(error) {
            reject(error);
          }
        );
      });
    }
    // Page API Call


    // API constants
    vm.apiConstants = {
      "catalog": {
        "inputTemplate": '{"request_data":{"inputs":{}},"request_meta":{"compiler_type":"Neuron"}}',
        "outputTemplate": [
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PDF One Pager",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CSO (Sustainability), CRO (Risk), CIO (Investment)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EUO-qVD-D5FHjLthahnSXmEBFJH5v7k6Dowp8F6CTan3Kw?e=jp6bM7",
      "External": "https://app.hubspot.com/documents/4052288/summary/5911476",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Solution Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CSO (Sustainability), CRO (Risk), CIO (Investment)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EWmQHy6T64RBr7bPIOosa5QBDI8994kYo_Gt5EDQOiKElQ?e=nXaL03",
      "External": "https://app.hubspot.com/documents/4052288/summary/5911477",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Demo Model (Carbon tax optimization)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CSO (Sustainability), CRO (Risk), CIO (Investment)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://spark.uat.us.coherent.global/coherent/shared/products/ESG",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'xCall', 'Data Consolidation', 'Goal Seek', 'Interactive Front End'",
      "Group ID": 1
    },
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Demo Front-end (Carbon tax optimization)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CSO (Sustainability), CRO (Risk), CIO (Investment)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentspark-esg-model.streamlit.app/",
      "External": null,
      "Video": null,
      "Features": "'xCall', 'Goal Seek', 'Interactive Front End'",
      "Group ID": 1
    },
    {
      "Topic Group": "Explainer",
      "Resource Name": "Explainer Intro Email Template",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Email Template",
      "Solution": "Explainer",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CAO (Actuary), CPO (Product), CMO (Marketing), Head of Transformation, CDO (Digital)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:w:/s/GTMPlanning/EbY4pt41VvFJlIyk1WyAIm4B87TRw9HZ3fYFoNZx03P6sw?e=62GfBV",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Explainer",
      "Resource Name": "Explainer Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Explainer",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CAO (Actuary), CPO (Product), CMO (Marketing), Head of Transformation, CDO (Digital)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/CoherentExplainer/EVMSdaac6yFMuLMrj3K_LNgB99fvGATGwxdJ6puVNy1DLQ?e=oAU05j",
      "External": "https://app.hubspot.com/documents/4052288/summary/5936457",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Explainer",
      "Resource Name": "Explainer Video",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Video",
      "Solution": "Explainer",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CAO (Actuary), CPO (Product), CMO (Marketing), Head of Transformation, CDO (Digital)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:v:/r/sites/CoherentExplainer/Shared%20Documents/General/Documents/Sales%20Deck/Coherent%20Explainer%20Edits%20v5.mp4?csf=1&web=1&e=tSJYWl",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Explainer",
      "Resource Name": "Explainer Solution Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Explainer",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CAO (Actuary), CPO (Product), CMO (Marketing), Head of Transformation, CDO (Digital)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/CoherentExplainer/EbnwipjljZ9Hh49WP1T1a_YBk2nhwn9c6a2q1Jxh0kWDbQ?e=PNBgav",
      "External": "https://app.hubspot.com/documents/4052288/summary/5936458",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Explainer",
      "Resource Name": "Explainer Templates Directory",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Demo Model",
      "Solution": "Explainer",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CAO (Actuary), CPO (Product), CMO (Marketing), Head of Transformation, CDO (Digital)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:f:/r/sites/CoherentExplainer/Shared%20Documents/General/Documents/Demo%20Materials/Explainer%20Demo%20Config%20Forms%20Per%20Release?csf=1&web=1&e=cvErly",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Data Illustration', 'Interactive Front End'",
      "Group ID": 4
    },
    {
      "Topic Group": "Explainer",
      "Resource Name": "Explainer Sample Front-End",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Explainer",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CAO (Actuary), CPO (Product), CMO (Marketing), Head of Transformation, CDO (Digital)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://explainer.uat.us.coherent.global/SL-1.2?tenant=explainer&service_uuid=d4bfa415-467a-4055-bd2f-9c2756759e41#/",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Data Illustration', 'Interactive Front End'",
      "Group ID": 4
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Credit Risk UW (Loan Origination LO) Solution Pitch",
      "Description / Notes": "Credit Scoring, loan eligibility calculation and loan offers are processed manually on excel by some of the lending companies and mid-tier banks. Spark offers a strong proposition to help audit the credit risk underwriting process and faster turnaround time for customer applications. Other key Benefit: Speed to Market to launch new products (fast prototyping and launch)",
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": "COO, CRO (Risk), Head of Credit Risk, CPO (Product), Unnamed record",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EYCYRHDHcMlHvzApKT5xhoUBJmAcMkXHKaf20sSBXvJCGQ?e=wao81a",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Credit Risk UW (Loan Origination) Overview",
      "Description / Notes": "Credit Scoring, loan eligibility calculation and loan offers are processed manually on excel by some of the lending companies and mid-tier banks. Spark offers a strong proposition to help audit the credit risk underwriting process and faster turnaround time for customer applications. Other key Benefit: Speed to Market to launch new products (fast prototyping and launch)",
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": "COO, CRO (Risk), Head of Credit Risk, CPO (Product)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EYN-rZGI9a5JtGJrawdvDy8BBzl7OOYM1dd2RJ70tb1IMg?e=r6j3cQ",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Credit Risk UW(Loan Origination)  Solution Brief",
      "Description / Notes": "Credit Scoring, loan eligibility calculation and loan offers are processed manually on excel by some of the lending companies and mid-tier banks. Spark offers a strong proposition to help audit the credit risk underwriting process and faster turnaround time for customer applications. Other key Benefit: Speed to Market to launch new products (fast prototyping and launch)",
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": "COO, CRO (Risk), Head of Credit Risk, CPO (Product)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/ERwPD4DgAC1Iq1jctSBG1AwBfeJYHyM9JW4FZkUJ7vDslQ?e=knbcXa",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Credit Risk UW (Loan Origination) video",
      "Description / Notes": "Credit Scoring, loan eligibility calculation and loan offers are processed manually on excel by some of the lending companies and mid-tier banks. Spark offers a strong proposition to help audit the credit risk underwriting process and faster turnaround time for customer applications. Other key Benefit: Speed to Market to launch new products (fast prototyping and launch)",
      "Sensitivity": "External",
      "Resource Type": "Video",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": "COO, CRO (Risk), Head of Credit Risk, CPO (Product)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://resources.coherent.global/content/lending-demo-video/",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Credit Risk UW (Loan Origination) Case Study",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": "COO, CRO (Risk), Head of Credit Risk, CPO (Product)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EbEAtkPxB-5MuNE09tT7VEMBLW5so2aKh8_aOJTN6I7UDQ?e=CuAXAy",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Credit Risk UW Demo excel (Retail Loan Origination)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": "COO, CRO (Risk), Head of Credit Risk, CPO (Product)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:x:/s/GTMPlanning/EfrNdvAyYE5IqAqMHN_SmqABJcnbFTgNB9sF1jiTfBGNzA?e=zQpINu",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Interactive Front End'",
      "Group ID": 3
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Credit Risk UW Demo Front-end (Retail Loan Origination)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": "COO, CRO (Risk), Head of Credit Risk, CPO (Product)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherent-demos-fs-cmb-loanorigination-streamlit-app-6rns7h.streamlit.app",
      "External": null,
      "Video": "https://coherentcapital.sharepoint.com/:v:/s/GTMPlanning/ESQ8u6nnTVdJpbpgCWisaPUB2XmZx1aNYh3nNgQhGS4jjA?e=2j7GWN",
      "Features": "'Complex Modelling',",
      "Group ID": 3
    },
    {
      "Topic Group": "Risk Modelling",
      "Resource Name": "Risk Modelling Overview",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "Model Control & Governance",
      "Industry": "Capital Markets",
      "Persona": "CRO (Risk), COO, CFO",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EeabA0rjJZhMrzyJ-IwasnMBtCWePx9H4X3xXdX4p43PcA?e=0zSG3G",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Risk Modelling",
      "Resource Name": "Risk Modelling Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Model Control & Governance",
      "Industry": "Capital Markets",
      "Persona": "CRO (Risk), COO, CFO",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EX7FaSsJDthLuipWuk7oxyMBtfjZkboWmCUci5r0Rjc2Ow?e=LaC1zq",
      "External": "https://app.hubspot.com/documents/4052288/summary/6108475",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Risk Modelling",
      "Resource Name": "Risk Modelling Solution Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Model Control & Governance",
      "Industry": "Capital Markets",
      "Persona": "CRO (Risk), COO, CFO",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EcXHJAM_vZdDkSBJwdaqkzwB9Z_5lP99MnzgzB6EHvZ8Ew?e=uPmVeu",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Actuarial Modelling",
      "Resource Name": "Actuarial Modelling Email Template",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Email Template",
      "Solution": "Actuarial Modelling",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CAO (Actuary), CFO",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:w:/s/GTMPlanning/EVQVI6qNyMFFs7IQIxieJ6gB3b0zZ8fZH06RKTZGA6bwag?e=gqUreD",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Actuarial Modelling",
      "Resource Name": "Actuarial Modelling Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Actuarial Modelling",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CAO (Actuary), CFO",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EQQXsvnKggFPqFxJWqKMiNkBlYN0NaBJo9Fo-11JCJjtTg?e=6zoN3G",
      "External": "https://app.hubspot.com/documents/4052288/summary/5911503",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Actuarial Modelling",
      "Resource Name": "Actuarial Modelling Gong (EY Asia)",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "Actuarial Modelling",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CAO (Actuary), CFO",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://us-53346.app.gong.io/call?id=1882010293771418457&highlights=%5B%7B%22type%22%3A%22SHARE%22%2C%22from%22%3A269%2C%22to%22%3A4303%7D%5D",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Actuarial Modelling",
      "Resource Name": "Actuarial Modelling Gong (Swisss Re)",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "Actuarial Modelling",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CAO (Actuary), CFO",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://us-53346.app.gong.io/call?id=9091704086844256489",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Actuarial Modelling",
      "Resource Name": "Actuarial Modelling Gong (New York Life)",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "Actuarial Modelling",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CAO (Actuary), CFO",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://us-53346.app.gong.io/call?id=9118878876274849971",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Client FAQ",
      "Resource Name": "Client Ready FAQ Deck",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Internal Ref",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EedoiKYRRVtPmKe_JsTdIxYBI2waz3rNNqTUX837-er6Aw?e=40xjs8",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Data Mgt",
      "Resource Name": "Data Management Solution Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Data Management",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CDO (Data), COO, CIO (Information), CISO (InfoSec), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EQnlyfZgcutJr0Hgm7NZFDEBv-i6WkD1gCiKOL6W462Zcg?e=QGMyEr",
      "External": "https://app.hubspot.com/documents/4052288/summary/6053148",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Data Mgt",
      "Resource Name": "Data Management Gong (UiPath)",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "Data Management",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CDO (Data), COO, CIO (Information), CISO (InfoSec), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": null,
      "External": null,
      "Video": "https://us-53346.app.gong.io/call?id=4572036226599888077",
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "EUC",
      "Resource Name": "EUC Overview",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "EUC (End User Computing)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CRO (Risk), CAO (Actuary), CTO, Office of Controllers",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EQWFFOeZsKxPu5YvGgMpi1EB3u3KgZo82ugAt3DjK5FZnA?e=FZwDkE",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "EUC",
      "Resource Name": "EUC Email Template",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Email Template",
      "Solution": "EUC (End User Computing)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CRO (Risk), CAO (Actuary), CTO, Office of Controllers",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:w:/s/GTMPlanning/ESIHQzkJPWBOvCJnObHcz3gBfzi6JkVd50osNZNQU8Bocw?e=ktbDJJ",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "EUC",
      "Resource Name": "EUC Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "EUC (End User Computing)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CRO (Risk), CAO (Actuary), CTO, Office of Controllers",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EYKBLsxcyKFLuuBS4O6FbjIBDqxWeufPQiGChvlepLs2hw?e=bsxcKN",
      "External": "https://app.hubspot.com/documents/4052288/summary/5911481",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "EUC",
      "Resource Name": "EUC Solution Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "EUC (End User Computing)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CRO (Risk), CAO (Actuary), CTO, Office of Controllers",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EcxgICBJ9WxDs2x9_ZRWxhQBXYDshYCG3coNGKTKLfNhZA?e=pKSnnz",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "EUC",
      "Resource Name": "EUC Demo (Spark)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "EUC (End User Computing)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CRO (Risk), CAO (Actuary), CTO, Office of Controllers",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://spark-euc.dev.coherent.global/coherent-euc/admin/eucAdmin ",
      "External": null,
      "Video": null,
      "Features": "'EUC',",
      "Group ID": 5
    },
    {
      "Topic Group": "EUC",
      "Resource Name": "EUC Demo (Script)",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Demo Front-End",
      "Solution": "EUC (End User Computing)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CRO (Risk), CAO (Actuary), CTO, Office of Controllers",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:w:/s/GTMPlanning/EVXuoag1yjFFg-RpNpweavUBrOwwuT2EJtU_7g_EMvWslQ?e=eMHgE8",
      "External": null,
      "Video": null,
      "Features": "'EUC',",
      "Group ID": 5
    },
    {
      "Topic Group": "Finance",
      "Resource Name": "Finance Overview",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "Finance",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CFO, Office of Controllers, CAO (Actuary)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/ESCJ0xIG3mVNtIMWZ9ShlyIBClW3ehuKvJbYguBNH4GkkA?e=sz0crd",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Finance",
      "Resource Name": "Finance Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Finance",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CFO, Office of Controllers, CAO (Actuary)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EdySQm8JkptMgUcVwkEfkd8BE6Sr1PQoySgJ-eyyWNjEsw?e=kr8eB2",
      "External": "https://app.hubspot.com/documents/4052288/summary/6053156",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Legacy",
      "Resource Name": "Legacy Modernization Overview",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "Legacy Modernisation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CTO, CIO (Information), COO, CDO (Digital), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/ETXId-KR9o1El2TVVrCSUwgBvqpRJaVn793ZnkkvZNwUdw?e=ZMnVfO",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Legacy",
      "Resource Name": "Legacy Modernization Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Legacy Modernisation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CTO, CIO (Information), COO, CDO (Digital), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EWzRfWu2Nv1HpCQcJIq2tZMBimXlkuKy5LM-3FvDBYtDUA?e=gJgmpE",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Legacy",
      "Resource Name": "Legacy Modernization Solution Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Legacy Modernisation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CTO, CIO (Information), COO, CDO (Digital), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/Edf-Q-NQthNPgdNeptglT4UBRe7cq8NxRXQIV8rTjBMRDA?e=5gexCv",
      "External": "https://app.hubspot.com/documents/4052288/summary/5911475",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Actuarial Modelling",
      "Resource Name": "Actuarial Modelling & IFRS17 Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Actuarial Modelling",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CAO (Actuary), CFO",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EY8bGXTQixJFtRh9rWPE33UB0s8HlunyvFt13Rx1NSJCCw?e=AJvAqp",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Legacy",
      "Resource Name": "Legacy Modernization DML Tool Video",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Video",
      "Solution": "Legacy Modernisation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CTO, CIO (Information), COO, CDO (Digital), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:v:/s/GTMPlanning/EfbTPDE1vPhNnO4sOxAPf74B0nOHQbpK3L39YCEGW5qK3w?e=kean52",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Modular",
      "Resource Name": "Modular Product Overview",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "Modular Product ",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CIO (Information), CTO, CPO (Product), CDO (Digital)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/Ee0JlBfUyOxBrAQ2tUeWy_QB0AxkuWE2PtowMpWwnp6W1A?e=GgZqOW",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Modular",
      "Resource Name": "Modular Product Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Modular Product ",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CIO (Information), CTO, CPO (Product), CDO (Digital)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/ERkMyyO2AJtOiLVM9KpcT08BoqssYaVtA1C-VeEqxKp-hw?e=88gXhz",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Pensions",
      "Resource Name": "Pensions eMPF Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Pensions | eMPF",
      "Industry": "Insurance: Life & Retirement/Annuity",
      "Persona": "Fund/Pensions Admin, Asset Managers",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EdgEEuZzr19Cjv6Dq2HFZGUBvejjXqvpMiKctag9kSY6gg?e=4UkZz7",
      "External": "https://app.hubspot.com/documents/4052288/summary/5941361",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Pensions",
      "Resource Name": "Pensions eMPF Solution Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Pensions | eMPF",
      "Industry": "Insurance: Life & Retirement/Annuity",
      "Persona": "Fund/Pensions Admin, Asset Managers",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EbusNqlYuK5LoyoL4KdcOMgBlBEya0gaWr6o9R-M6NlWgQ?e=sH2vI0",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Rating",
      "Resource Name": "Rating Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Rating / Quotation / Pricing",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "CIO (Information), CTO, CDO (Digital), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EbVex2PDHyRAsv2SAVsiXAsBVn_saGxcxb1u_8-dm4PE0w?e=nI4i25",
      "External": "https://app.hubspot.com/documents/4052288/summary/6108489",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Reconcillation",
      "Resource Name": "Reconciliation Overview",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "Reconciliation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CFO, Fund/Pensions Admin, Treasury",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EWQjaqMbdopGrN2IoPtZ4wgB-7-QthP-zL_zkKOkAYUIgg?e=Dcp8pN",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Reconcillation",
      "Resource Name": "Reconciliation Solution Brief",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Reconciliation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CFO, Fund/Pensions Admin, Treasury",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EcDy15aInbVNjkxKthpbZQsBKDs1x8sUzKqEUJ4T9JH7ZQ?e=qt1mvF",
      "External": "https://app.hubspot.com/documents/4052288/summary/5911478",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Reconcillation",
      "Resource Name": "Reconciliation Solution Pitch",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Reconciliation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CFO, Fund/Pensions Admin, Treasury",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/ESbV5983HVdFpYZqNlkxow4B9o3aCIPDBg0s2K2gX1oL4A?e=z7uFkQ",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Securities",
      "Resource Name": "Securities Services Overview",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "Securities Services",
      "Industry": "Capital Markets",
      "Persona": "COO, CAO (Actuary), CPO (Product), CTO",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EZHB3vaeQmJPjDngYWDSS4ABhA-l8zqEhD12STGErMLDJg?e=WEx0Ht",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Securities",
      "Resource Name": "Securities Services Solution Brief (Deal Pricing)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Securities Services",
      "Industry": "Capital Markets",
      "Persona": "COO, CAO (Actuary), CPO (Product), CTO",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EQiuro7Kka1ImGDu54CPMgkBZL4z-66bMJIHlVdSH05LXw?e=HQaXMa",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Securities",
      "Resource Name": "Securities Services Solution Brief (Generic)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Securities Services",
      "Industry": "Capital Markets",
      "Persona": "COO, CAO (Actuary), CPO (Product), CTO",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EZi379O7RB1PphUp-XOEpdIBlOEKJ3gt8N5ylkcmVAzC0A?e=Yd81oW",
      "External": "https://app.hubspot.com/documents/4052288/summary/6108474",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Securities",
      "Resource Name": "Securities Services Solution Pitch (Deal Pricing)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Securities Services",
      "Industry": "Capital Markets",
      "Persona": "COO, CAO (Actuary), CPO (Product), CTO",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EVXBO4-Uyz5OqkQUfZ99FmsBzKpKSdHR_a5JYDaTr-pwCQ?e=9KBFcu",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Securities",
      "Resource Name": "Securities Services Demo Video (Deal Pricing)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Video",
      "Solution": "Securities Services",
      "Industry": "Capital Markets",
      "Persona": "COO, CAO (Actuary), CPO (Product), CTO",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:v:/s/GTMPlanning/EfU-F7wMF5xFu91VZrTFxLkBxZ0WeBc44MNNPgWB25qP4w?e=itTYUI",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Securities",
      "Resource Name": "Securities Services Demo Model (Deal Pricing)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Securities Services",
      "Industry": "Capital Markets",
      "Persona": "COO, CAO (Actuary), CPO (Product), CTO",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://spark.uat.us.coherent.global/coherent/products/SS%20Test%20Usecases/Sample%20-%20SS%20Pricing%20template_mapped/serviceDocumentation/uploadSummary",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Interactive Front End'",
      "Group ID": 6
    },
    {
      "Topic Group": "Securities",
      "Resource Name": "Securities Services Demo Front-end (Deal Pricing)",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Demo Front-End",
      "Solution": "Securities Services",
      "Industry": "Capital Markets",
      "Persona": "COO, CAO (Actuary), CPO (Product), CTO",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://sspricingtemplate-sandbox.mxapps.io/",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Interactive Front End'",
      "Group ID": 6
    },
    {
      "Topic Group": "VBA FAQ",
      "Resource Name": "[FAQ] Does Spark support VBA?",
      "Description / Notes": "#VBA",
      "Sensitivity": "Internal",
      "Resource Type": "HubSpot Snippet",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://app.hubspot.com/snippets/4052288/edit/2469808?folder=516669&page=1",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "References",
      "Resource Name": "Pricing Strategy",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Internal Ref",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/Efs9vsu2YcVIj7K7vRXd2xQBJakZFnLntpcoqdj6Zh-xaA?e=2bfeyK",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "References",
      "Resource Name": "EY Intependence Form (Filled Sample Reference)",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Internal Ref",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://coherentcapital-my.sharepoint.com/:w:/g/personal/amy_ma_coherent_global/EV0ZACh6DwhIn2w7YTqqOCcBHTcrcHXSVvIaWhr9FfcdtQ?e=Y15Ba9",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "References",
      "Resource Name": "Global Case Studies",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Internal Ref",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/ESVTVB15iWNJibfGxxJvuTUBAVq0lGsBM8Avspj0q7hH_g?e=gzdkoe",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "References",
      "Resource Name": "Shortlisted Case Studies (Cross Sector)",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Internal Ref",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/CoherentSales/EQ2MHY-QRlJDjGGZ0DCArmcBMMJMbIiVJnBRUdtX9USfrg?e=mvH6cz",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "References",
      "Resource Name": "Coherent Contract Templates",
      "Description / Notes": "Templates for:\n- NDA\n- Master License Agreement\n- SOW\n- Letter of Intent\n- Partnership Agreement\n- Starter Tenant\n- Project Agreement\n\nNote: There may be different templates for US versus NON-US, as well as some templates specific to a unique country. ",
      "Sensitivity": "Internal",
      "Resource Type": "Internal Ref",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:f:/s/BillingsandContracts/Eg0s6YUFlI5JvrOQDI3h2XIBxBHTKgEso65oVyG3y_4n5w",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Solution Overview",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Internal Ref",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CSO (Sustainability), CRO (Risk), CIO (Investment)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/ES6BazUa-cNBkIXAyUXOSs8BzAZSHKsDaqwVPyXK1v2-aw?e=QDJN5G",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "EUC",
      "Resource Name": "EUC Solution Deep Dive",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "EUC (End User Computing)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CRO (Risk), CAO (Actuary), CTO, Office of Controllers",
      "Pricing": "Models Stored",
      "Internal Sharepoint": "https://us-53346.app.gong.io/call?id=7724408862539474820&xtid=5ftk06cza2t9oqx6lno",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Loan Origination Solution Deep Dive",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": "COO, CRO (Risk), Head of Credit Risk, CPO (Product)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://us-53346.app.gong.io/call?id=3659757998097092881&xtid=7n7i7m2jairl1deize9",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Reconciliation Solution Deep Dive",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "Reconciliation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "COO, CFO, Fund/Pensions Admin, Treasury",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://us-53346.app.gong.io/call?id=6754232489124813087&xtid=5rlzjakw14frx0tmq88",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Legacy",
      "Resource Name": "Legacy Modernization Solution Deep Dive",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "Legacy Modernisation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CTO, CIO (Information), COO, CDO (Digital), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://us-53346.app.gong.io/call?id=7907436144309580545&xtid=5yn2b1alm70803u3mjp",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Insurance",
      "Resource Name": "Insurance Sector Intro",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EXMGbYe1TFVPhXV-ExGnZD8BTK0tGL863swcSfkV40iMlQ?e=WDWYX4",
      "External": "https://app.hubspot.com/documents/4052288/summary/5911465",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "BCM",
      "Resource Name": "Banking & Capital Markets Sector Intro",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "Banking, Capital Markets",
      "Persona": "_ALL PERSONAS",
      "Pricing": "_ALL PRICING MODELS",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/EUNnR1AmgfRAimn8PyIH8a4B6AihBKhYHNsFE1SlVwgZGg?e=hkO2e6",
      "External": "https://app.hubspot.com/documents/4052288/summary/5992553",
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Legacy",
      "Resource Name": "Legacy Modernization Video",
      "Description / Notes": "Coherent branded - new branding",
      "Sensitivity": "External",
      "Resource Type": "Video",
      "Solution": "Legacy Modernisation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CTO, CIO (Information), COO, CDO (Digital), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": null,
      "External": null,
      "Video": "https://resources.coherent.global/content/legacy-modernization-with-spark/",
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Solution Deep Dive",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "Gong Call",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CSO (Sustainability), CRO (Risk), CIO (Investment)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://us-53346.app.gong.io/call?id=8589206571113212441",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Demo Model (Portfolio Analytics)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES, Capital Markets, Banking",
      "Persona": "Asset Managers, CIO (Investment), CRO (Risk), CSO (Sustainability)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://spark.staging.coherent.global/coherent/products/ESG%20Investment%20Screening",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'xCall', 'Data Consolidation', 'Goal Seek', 'Data Illustration', 'Interactive Front End'",
      "Group ID": 2
    },
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Demo Front-end (Portfolio Analytics)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES, Capital Markets, Banking",
      "Persona": "Asset Managers, CIO (Investment), CRO (Risk), CSO (Sustainability)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentspark-esg-screener.streamlit.app/",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'xCall', 'Data Consolidation', 'Goal Seek', 'Data Illustration', 'Interactive Front End'",
      "Group ID": 2
    },
    {
      "Topic Group": "Feature",
      "Resource Name": "Introducing Coherent XCall",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Video",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": null,
      "Internal Sharepoint": null,
      "External": null,
      "Video": "https://resources.coherent.global/?s=xcall&wpessid=990613",
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "References",
      "Resource Name": "Portfolio Optimization Tool",
      "Description / Notes": null,
      "Sensitivity": null,
      "Resource Type": null,
      "Solution": null,
      "Industry": null,
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://portfoliooptimization.showcase.coherent.global/",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "References",
      "Resource Name": "New Corporate Intro Deck (7 June)",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": null,
      "Industry": null,
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/g/EZbWN_SgBd1PibJKzO9CJXIBe0gNsn4_t4y6vsffG7SpHA?e=1TGWLd",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "ESG",
      "Resource Name": "ESG Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "ESG (Modelling and Reporting)",
      "Industry": "_ALL INDUSTRIES",
      "Persona": "_ALL PERSONAS",
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/esg-modelling-with-no-compromises-2/?c=cG9zdDo5OTE2NDM=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Modular",
      "Resource Name": "Modular Insurance (Cross Sector) Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "Modular Product ",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C, Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/modular-insurance/?c=cG9zdDo5OTE4MTc=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Cross Sector",
      "Resource Name": "Excel as a Programming Language (Cross Sector) Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/excel-as-a-programming-language-2/?c=cG9zdDo5OTE4Mzk=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Digital Bank",
      "Resource Name": "Digibank Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "Finance, EUC (End User Computing)",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/digibank/?c=cG9zdDo5OTEzNTg=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Actuarial Modelling",
      "Resource Name": "Actuarial 3.0 Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "Actuarial Modelling",
      "Industry": "Insurance: P&C, Insurance: Life & Retirement/Annuity",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/actuary3-0-ebook/?c=cG9zdDo5OTE4OTI=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "BCM",
      "Resource Name": "BCM Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "EUC (End User Computing), Finance, Legacy Modernisation, Loan Origination , Reconciliation, Securities Services",
      "Industry": "Banking, Capital Markets",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/banking-and-capital-markets/?c=cG9zdDo5OTE4OTY=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Insurance",
      "Resource Name": "Insurance Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "Actuarial Modelling, Legacy Modernisation, Modular Product , Rating / Quotation / Pricing",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/insurance/?c=cG9zdDo5OTE5MjA=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Modular",
      "Resource Name": "Modular Insurance with Spark Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "Modular Product ",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/modular-insurance-with-spark/?c=cG9zdDo5OTE4MjA=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Securities",
      "Resource Name": "Secure 2.0 Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "Pensions | Secure 2.0",
      "Industry": "Wealth & Asset Management",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/secure-2-0-update/?c=cG9zdDo5OTEzNjM=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "References",
      "Resource Name": "Onboarding Series Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "_ALL SOLUTIONS / USE CASES",
      "Industry": "_ALL INDUSTRIES",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/onboarding-series/?c=cG9zdDo5OTE2OTg=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Legacy",
      "Resource Name": "Legacy Modernization Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "Legacy Modernisation",
      "Industry": "Insurance: Life & Retirement/Annuity, Insurance: P&C, Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/legacy-modernization/?c=cG9zdDo5OTE0NzY=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Data Mgt",
      "Resource Name": "Data Management Znglist",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Znglist",
      "Solution": "Data Management",
      "Industry": "_ALL INDUSTRIES",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://resources.coherent.global/znglist/data-management-with-spark/?c=cG9zdDo5OTIwMjc=",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Legacy",
      "Resource Name": "Cognizant co-branded Legacy Modernization Video",
      "Description / Notes": "Co-branded with Cognizant",
      "Sensitivity": "External",
      "Resource Type": "Video",
      "Solution": "Legacy Modernisation",
      "Industry": "_ALL INDUSTRIES, Banking, Insurance: Life & Retirement/Annuity, Capital Markets, Insurance: P&C, Other Industries, Wealth & Asset Management",
      "Persona": "CTO, CIO (Information), COO, CDO (Digital), CPO (Product)",
      "Pricing": "API Services",
      "Internal Sharepoint": "https://onedrive.live.com/?authkey=%21ADEf41vv1KMOpyI&id=C7DD9FC33EDA6791%21442&cid=C7DD9FC33EDA6791&parId=root&parQt=sharedby&o=OneUp",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Banking Stress Test",
      "Resource Name": "Bank Stress Testing Demo - Spark UI",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://spark.uat.us.coherent.global/coherent/products/Spark%20FE%20Demos/banking-stress-test/serviceDocumentation/uploadSummary",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'xCall', 'Data Consolidation', 'Data Illustration', 'Interactive Front End'",
      "Group ID": 7
    },
    {
      "Topic Group": "Banking Stress Test",
      "Resource Name": "Bank Stress Testing Demo - Front End",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "coherent-demos-fs-cmb-stresstest-streamlit-app-13rqyd.streamlit.app/",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'xCall', 'Data Consolidation', 'Data Illustration', 'Interactive Front End'",
      "Group ID": 7
    },
    {
      "Topic Group": "Banking Stress Test",
      "Resource Name": "Bank Stress Testing Demo - PPT Guide",
      "Description / Notes": null,
      "Sensitivity": "Internal",
      "Resource Type": "PPT Deck",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/SalesEngineering/EezWnGZNq9xGqfKghcSHmLsBDnKLV51Nshg7bJsmm27Zgg?e=wj7fzk",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "Digital Bank",
      "Resource Name": "Digital Bank Embedded Insurance Demo - Spark UI",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://spark.staging.coherent.global/coherentflex/products/Bill%",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'xCall', 'Interactive Front End'",
      "Group ID": 8
    },
    {
      "Topic Group": "Digital Bank",
      "Resource Name": "Digital Bank Embedded Insurance Demo - Front End",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://coherentdemos.com/",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'xCall', 'Interactive Front End'",
      "Group ID": 8
    },
    {
      "Topic Group": "Digital Bank",
      "Resource Name": "Personalized Embedded Insurance Use Case with mock-up screens",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "PPT Deck",
      "Solution": "Finance",
      "Industry": "Insurance: P&C",
      "Persona": "CCO (Customer), CDO (Digital), CPO (Product)",
      "Pricing": "API Calls",
      "Internal Sharepoint": "https://coherentcapital.sharepoint.com/:p:/s/GTMPlanning/ERmSsslGGuROih_H9vDIZqsBZ6rrfr14gVtNeIrp9m8H9g?e=SIn6KY",
      "External": null,
      "Video": null,
      "Features": null,
      "Group ID": null
    },
    {
      "Topic Group": "ECL",
      "Resource Name": "Expected Credit Loss Calculator - Demo",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://expectedcreditlosscalc.showcase.coherent.global/",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Data Illustration', 'Interactive Front End'",
      "Group ID": 9
    },
    {
      "Topic Group": "ECL",
      "Resource Name": "Expected Credit Loss Calculator - Spark UI",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://spark.uat.us.coherent.global/coherent/products/Agilno%20Powered%20by%20Spark/ECL%20model_Revolving%20Calculation%20and%20ECL%20Model_PR/apiTester/test",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Data Illustration', 'Interactive Front End'",
      "Group ID": 9
    },
    {
      "Topic Group": "Insurance",
      "Resource Name": "Cyber Insurance Rater - Demo",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Finance",
      "Industry": "Insurance: P&C",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://cyberinsurancerater.demo.coherent.global/",
      "External": null,
      "Video": null,
      "Features": "'Interactive Front End'",
      "Group ID": 10
    },
    {
      "Topic Group": "Insurance",
      "Resource Name": "Cyber Insurance Rater - Spark UI",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Finance",
      "Industry": "Insurance: P&C",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://spark.uat.us.coherent.global/coherent/products/Agilno%20Powered%20by%20Spark/DEMOS_Agilno_CyberRater/apiTester/test",
      "External": null,
      "Video": null,
      "Features": "'Interactive Front End'",
      "Group ID": 10
    },
    {
      "Topic Group": "Finance",
      "Resource Name": "Bond Valuation Calculator - Demo",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://bondvaluecalc.showcase.coherent.global/",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Interactive Front End'",
      "Group ID": 11
    },
    {
      "Topic Group": "Finance",
      "Resource Name": "Bond Valuation Calculator - Spark UI",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Finance",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://spark.uat.us.coherent.global/coherent/products/Agilno%20Powered%20by%20Spark/Bond%20valuation%20calculator_Bond%20MV%20Calc%20(2)/apiTester/test",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Interactive Front End'",
      "Group ID": 11
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Home Affordability Calculator - Demo",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://homeaffordabilitycalc.showcase.coherent.global/",
      "External": null,
      "Video": null,
      "Features": "'Interactive Front End'",
      "Group ID": 12
    },
    {
      "Topic Group": "Loan",
      "Resource Name": "Home Affordability Calculator - Spark UI",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Loan Origination ",
      "Industry": "Banking",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://spark.uat.us.coherent.global/coherent/products/Agilno%20Powered%20by%20Spark/DEMOS_home_affordability/apiTester/test",
      "External": null,
      "Video": null,
      "Features": "'Interactive Front End'",
      "Group ID": 12
    },
    {
      "Topic Group": "Finance",
      "Resource Name": "401k Calculator - Demo",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Front-End",
      "Solution": "Pensions",
      "Industry": "Insurance: P&C",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://401calc.showcase.coherent.global/",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Interactive Front End'",
      "Group ID": 13
    },
    {
      "Topic Group": "Finance",
      "Resource Name": "401k Calculator - Spark UI",
      "Description / Notes": null,
      "Sensitivity": "External",
      "Resource Type": "Demo Model",
      "Solution": "Pensions",
      "Industry": "Insurance: P&C",
      "Persona": null,
      "Pricing": null,
      "Internal Sharepoint": "https://spark.uat.us.coherent.global/coherent/products/Agilno%20Powered%20by%20Spark/DEMOS_Spark_401k_Pricing_Model/apiTester/test",
      "External": null,
      "Video": null,
      "Features": "'Complex Modelling', 'Interactive Front End'",
      "Group ID": 13
    }
  ],
        "apikey": "2277565c-9fad-4bf4-ad2b-1efe5748dd11",
        "tenant": "coherent",
        "url": "https://excel.uat.us.coherent.global/coherent/api/v3/folders/Spark FE Demos/services/demo-catalog/Execute"
      }
    }
  }
})();

